destination = '$HOME'
source = '$HOME/.local/share/donut'
diff = ['diff', '-upN', '{{.Destination}}', '{{.Source}}']
editor = ["nvim"]
pager = ["delta"]
merge = ["nvim", "-d", "{{.Destination}}", "{{.Source}}"]
excludes = [
  ".gitignore",
  "scripts",
  "README.md",
  "LICENSE",
  "Brewfile",
  "app.md",
  "my.rayconfig",
]
